### ISSUE TITLE
python-hidapi-0.9.0.post3 fails to build on Fedora 33 with Python 3.9.0b4

### ISSUE THREAD

**Issue by hegjon** [trezor/cython-hidapi#92] opened 2020-07-10 14:19 UTC
It seems to fail during tests, there is one warning during build. 0.9.0.post2 build successful.

Build log: https://kojipkgs.fedoraproject.org//work/tasks/618/46930618/build.log
Build info: https://koji.fedoraproject.org/koji/taskinfo?taskID=46930618

### Version:
```
DEBUG util.py:623:   hidapi-devel               x86_64    0.9.0-3.fc32               build     12 k
DEBUG util.py:623:   libusb-devel               x86_64    1:0.1.7-1.fc33             build     12 k
DEBUG util.py:623:   python3-Cython             x86_64    0.29.19-1.fc33             build    2.1 M
DEBUG util.py:623:   python3-devel              x86_64    3.9.0~b4-1.fc33            build    204 k
DEBUG util.py:623:   python3-setuptools         noarch    47.3.1-1.fc33              build    598 k
```

**Comment by hegjon** [comment] 2020-07-10 14:21
Related to issue #90 ?

**Comment by prusnak** [comment] 2020-07-10 14:25
Yes, this is duplicate of #90 

Either revert https://github.com/trezor/cython-hidapi/commit/cd2b2878b4299d4be63e090b6eaf572276f6e4f1 from your cython-hidapi package or use libhidapi from master.

**Closed by prusnak** 2020-07-10 14:25 UTC

**Comment by hegjon** [comment] 2020-07-10 14:44
Thanks will use 0.9.0.post2 instead
