### ISSUE TITLE
Path format changed in v0.14.0.post4

### ISSUE THREAD

**Issue by robin-nitrokey** [trezor/cython-hidapi#191] opened 2024-12-13 10:04 UTC
In [pynitrokey](https://github.com/nitrokey/pynitrokey), we run into the following error with v0.14.0.post4:

```
Traceback (most recent call last):
  File "/home/robin/reps/pynitrokey/venv/lib/python3.11/site-packages/nitrokey/trussed/_bootloader/lpc55_upload/utils/interfaces/device/usb_d
evice.py", line 78, in open
    self._device.open_path(self.path)
  File "hid.pyx", line 158, in hid.device.open_path
OSError: open failed
```

I managed to reproduce the problem with this script:

```python3
import hid

devices = hid.enumerate()
print("paths: ")
print([d["path"] for d in devices])

for device in devices:
    if device["vendor_id"] == 0x20a0 and device["product_id"] == 0x42dd:
        h = hid.device()
        h.open_path(device["path"])
        h.close()
```

With post2 and post3, I get the following output:

```text
paths:
[b'/dev/hidraw4', b'/dev/hidraw0', b'/dev/hidraw1', b'/dev/hidraw2', b'/dev/hidraw2', b'/dev/hidraw3', b'/dev/hidraw3', b'/dev/hidraw3']
```

But with post4, the path format changes and opening the device fails:

```text
paths:
[b'1-10.2:1.0', b'1-10.2:1.1', b'1-10.1:1.0', b'1-1.4.3:1.0', b'1-1.1:1.0']
Traceback (most recent call last):
  File "/home/robin/reps/pynitrokey/test-hid.py", line 11, in <module>
    h.open_path(device["path"])
  File "hid.pyx", line 158, in hid.device.open_path
OSError: open failed
```

I am able to fix the problem by adding a new udev rule.  We previously had this rule:

```text
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="42dd", TAG+="uaccess"
```

This rule fixes it:
```text
ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="42dd", MODE="666"
````

I also tried this but it was not enough:
```text
ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="42dd", TAG+="uaccess"
```

I’m not sure what causes this change and why the `uaccess` rule no longer works.  Still, I think it is unexpected for a post release to cause such a change.  Is it possible to revert this change?

**Comment by prusnak** [comment] 2024-12-13 10:14
post2 and post3 are yanked because they used hidraw paths 

this caused issues so I returned back to libusb paths which were used prior post2

**Comment by robin-nitrokey** [comment] 2024-12-13 10:15
Only post3 is yanked.  Isn’t post4 supposed to be the revert to post2?

**Comment by prusnak** [comment] 2024-12-13 10:18
> Isn’t post4 supposed to be the revert to post2?

right, yes

you mixed two issues in one and i was confused

so there is still the `uaccess` issue - can you reproduce on several machines? if yes, then please open a new issue and I will close this once since the path format change is expected

**Closed by prusnak** 2024-12-13 10:18 UTC

**Comment by robin-nitrokey** [comment] 2024-12-13 10:19
I’m pretty sure I did not mix it.  post2 and post3 show the hidraw paths, even if path2 should be using the libusb backend.

**Comment by prusnak** [comment] 2024-12-13 10:27
> path2 should be using the libusb backend.

🤷  not sure what is happening, but the point is that we have to keep using libusb backend because many people rely on that (basically the same situation you hit, but in reverse)

**Comment by prusnak** [comment] 2024-12-13 12:34
> I guess we need to restrict the dependency to `> post1, < post4` for the time being.

Do you need hidraw backend? All rest of the world is stuck with libusb backend.

> And the issue with the udev rules is probably an issue with libhidapi itself, right?

No idea. It seems really weird.

**Comment by robin-nitrokey** [comment] 2024-12-13 12:43
We have received several reports that the update to post4 caused this problem on different systems (Ubuntu, Debian, Fedora, NixOS), probably because the udev rules that we have recommended do not work with libusb.  It will take some time to roll out the new udev rules (once we have found a way that works with `uaccess`), and we cannot ship them directly with the application.  So I think restricting the hidapi version is the best way to fix this problem for end users at the moment.

**Comment by bearsh** [comment] 2024-12-13 13:33
@prusnak as the backend discussion seems to pup up every other week and AFAIK it was possible in the past, what about shipping both backends again? so everyone can choose which backend to use. (of course, someone needs to volunteer to provide a PR...)

**Comment by prusnak** [comment] 2024-12-13 14:49
It popped up twice because I changed the backend twice (forth and back). Unless we change the default backend, it will not pop up again. Also you can use the hidraw backend if you do "import hidraw as hid" (only works on linux).

**Comment by bearsh** [comment] 2024-12-13 16:41
> It popped up twice because I changed the backend twice (forth and back). Unless we change the default backend, it will not pop up again. Also you can use the hidraw backend if you do "import hidraw as hid" (only works on linux).

sorry, didn't know this still works...
