### ISSUE TITLE
add supporting for hid_get_report_descriptor

### ISSUE THREAD

**Issue by sinseraph** [trezor/cython-hidapi#172] opened 2024-02-07 05:39 UTC
Please add a API fucntion according to new feature in hidapi-0.14.0
general: add hid_get_report_descriptor API function (https://github.com/libusb/hidapi/pull/451)

I need report_descriptor to figure out different bLength of multiple enumerates, thanks.

**Comment by prusnak** [comment] 2024-02-07 10:59
Duplicate of https://github.com/trezor/cython-hidapi/issues/165

**Closed** 2024-02-07 10:59 UTC
