### ISSUE TITLE
hid import error with macos Catalina (10.15.4) and Anaconda Python 3.7.7.

### ISSUE THREAD

**Issue by GoJian** [trezor/cython-hidapi#82] opened 2020-04-15 02:17 UTC
Hi -

I seek help tracking down an issue on macOS Catalina (10.5.4) using Anaconda Python 3.7.7. Everything else is up to date. The original issue was posted with the Adafruit_Blinka library, [#271](https://github.com/adafruit/Adafruit_Blinka/issues/271). However, after some initial investigation, I believe the issue is with the hidapi library. The error happens during the "import hid" command, which throws out an error about unknown symbols: Symbol not found: ___CFConstantStringClassReference.

More detailed info regarding the libraries on my system:

Python 3.7.7 (default, Mar 26 2020, 10:32:53)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin

hidapi 0.9.0.post2 pypi_0 pypi
adafruit-blinka 4.3.0 pypi_0 pypi
adafruit-platformdetect 2.5.0 pypi_0 pypi
adafruit-pureio 1.1.0 pypi_0 pypi

So I began to build the hidapi library myself, but I kept getting warnings such that:

```
IOKit.framework/IOKit.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64). 
```
The resulting library, after installation, gives the [same exact error](https://github.com/adafruit/Adafruit_Blinka/issues/271) during "import hid".

I have limited knowledge and skill in finding the exact issue here. This issue has been with me for a few months. I do have Xcode installed but haven't used it that much and don't know if that is relevant. Thanks for your help and pointers! Let me know what more information do you need, please.

Complete build shell block pasted down below:
```
cython-hidapi % python setup.py build
running build
running build_ext
cythoning hid.pyx to hid.c
/Users/gojian/Programs/Anaconda/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/gojian/Programs/cython-hidapi/hid.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'hid' extension
creating build
creating build/temp.macosx-10.9-x86_64-3.7
creating build/temp.macosx-10.9-x86_64-3.7/hidapi
creating build/temp.macosx-10.9-x86_64-3.7/hidapi/mac
x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/gojian/Programs/Anaconda=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -framework IOKit -framework CoreFoundation -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -Ihidapi/hidapi -I/Users/gojian/Programs/Anaconda/include/python3.7m -c hid.c -o build/temp.macosx-10.9-x86_64-3.7/hid.o
clang-4.0: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
clang-4.0: warning: -framework IOKit: 'linker' input unused [-Wunused-command-line-argument]
clang-4.0: warning: -framework CoreFoundation: 'linker' input unused [-Wunused-command-line-argument]
x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/gojian/Programs/Anaconda=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -framework IOKit -framework CoreFoundation -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -Ihidapi/hidapi -I/Users/gojian/Programs/Anaconda/include/python3.7m -c hidapi/mac/hid.c -o build/temp.macosx-10.9-x86_64-3.7/hidapi/mac/hid.o
clang-4.0: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
clang-4.0: warning: -framework IOKit: 'linker' input unused [-Wunused-command-line-argument]
clang-4.0: warning: -framework CoreFoundation: 'linker' input unused [-Wunused-command-line-argument]
hidapi/mac/hid.c:267:20: warning: comparison of integers of different signs: 'CFIndex' (aka 'long') and 'size_t' (aka 'unsigned long') [-Wsign-compare]
                if (chars_copied == len)
                    ~~~~~~~~~~~~ ^  ~~~
1 warning generated.
creating build/lib.macosx-10.9-x86_64-3.7
x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/gojian/Programs/Anaconda/lib -L/Users/gojian/Programs/Anaconda/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/gojian/Programs/Anaconda/lib -L/Users/gojian/Programs/Anaconda/lib -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -framework IOKit -framework CoreFoundation -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/hid.o build/temp.macosx-10.9-x86_64-3.7/hidapi/mac/hid.o -o build/lib.macosx-10.9-x86_64-3.7/hid.cpython-37m-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks//IOKit.framework/IOKit.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks//IOKit.framework/IOKit.tbd
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd
```

**Comment by prusnak** [comment] 2020-04-15 07:23
Simple Google search for "0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33" reveals this is a clash between Anaconda and macOS SDK.

As I don't have a macOS I can only recommend you to use regular Python.

Closing as this is not a bug in the library.

**Closed by prusnak** 2020-04-15 07:23 UTC
