### ISSUE TITLE
hid_enumerate returns empty paths on macOS Mojave and Catalina

### ISSUE THREAD

**Issue by conurus** [trezor/cython-hidapi#77] opened 2020-01-20 02:37 UTC
This only happens on Mojave and Catalina and also the app is in a sandbox signed with hardened runtime. I tried this fix in libusb/hidapi and it worked so it is just a matter using that label: https://github.com/libusb/hidapi/pull/120

**Comment by prusnak** [comment] 2020-01-20 12:25
Duplicate of https://github.com/trezor/cython-hidapi/issues/65

**Comment by prusnak** [comment] 2020-01-20 12:25
Can you try building the version from master to see if it works for you?

**Closed by prusnak** 2020-01-20 12:25 UTC
